config {
    type: "assertion",
    schema: "silver"
}

  /*
  * This code ensures the following data quality checks
  * "Ensure 'month' and 'traffic_source_medium' are not null."
  * "Ensure 'event_date' contains valid date values."
  */
SELECT
  COUNT(*) AS null_format_check
FROM
  ${ref("purchase_traffic_source_medium")}
WHERE
  SAFE.PARSE_DATE('%Y%m%d', event_date) IS NULL
  OR event_date IS NULL
  OR traffic_source_medium IS NULL
HAVING
  null_format_check >0
