config {
    type: "table",
    schema: "silver",
    description: "This is to create a clean/denormalized data from vw_stg_raw_events view"
}

  /**
  * This code performs data cleaning and transformation to populate purchase_traffic_source_medium using view vw_stg_raw_events.
  *
  * Key transformations:
  * - Filters out events other than purchase and traffic source from data deleted.
  * - Extract the 'ga_session_id' from the 'event_params' array.
  **/
  -- Create a table with clean data
SELECT
  event_date,
  traffic_source.medium AS traffic_source_medium,
  user_pseudo_id,
  ep.value.int_value AS ga_session_id,
  event_value_in_usd,
  ecommerce.total_item_quantity AS total_purchased_items
FROM
  ${ref("vw_stg_raw_events")},
  UNNEST(event_params) AS ep
WHERE
  ep.key = 'ga_session_id'
  AND LOWER(event_name) = 'purchase'
  AND LOWER(traffic_source.medium) != '(data deleted)' 
