config {
    type: "table",
    schema: "silver",
    description: "This is to create a clean/denormalized data from vw_stg_raw_events view"
}

  /**
  * This code performs data cleaning and transformation to populate purchase_traffic_source_medium using view vw_stg_raw_events.
  *
  * Key transformations:
  * - Filters out events other than purchase and traffic source from data deleted.
  * - Extract the 'ga_session_id' from the 'event_params' array.
  **/
  -- Create a table with clean data
WITH
  raw_source AS (
  SELECT
    *
  FROM
    ${ref("vw_stg_raw_events")} )
SELECT
  event_date,
  traffic_source.medium AS traffic_source_medium,
  user_pseudo_id,
  CAST((
    SELECT
      value.int_value
    FROM
      UNNEST(event_params)
    WHERE
      KEY = 'ga_session_id'
    LIMIT
      1) AS INT) AS ga_session_id,
  event_value_in_usd,
  ecommerce.unique_items AS total_purchased_items
FROM
  raw_source
WHERE
  LOWER(event_name) = 'purchase'
  AND LOWER(traffic_source.medium) != '(data deleted)'
