config {
    type: "table",
    schema: "gold",
    description: "This is to create a business table report from purchase_traffic_source_medium"
}

  /**
  * This Table report analyzing which traffic_source_medium was responsible for the most value and volume.
  * This code aggregates clean events data by month, traffic_source_medium.
  *
  * Key transformations:
  * - Aggregates purchased value, total number of purchases and average number of purchases by month, traffic_source_medium.
  **/
  -- Create a table with report data
WITH
  agg AS (
  SELECT
    FORMAT_DATE('%Y-%m', PARSE_DATE('%Y%m%d', event_date)) AS month,
    traffic_source_medium,
    SUM(event_value_in_usd) AS purchased_value_in_usd,
    SUM(total_purchased_items) AS total_purchased_items,
    COUNT(*) AS total_no_purchases,
  FROM
    ${ref("purchase_traffic_source_medium")}
  GROUP BY
    month,
    traffic_source_medium ) // Assertions FOR DATA validation
ASSERT
  ("no_null_month_traffic_source_medium",
    `
  SELECT
    COUNT(*)
  FROM
    agg
  WHERE
    month IS NULL
    OR traffic_source_medium IS NULL `) { description: "Ensure 'month' and 'traffic_source_medium' are not null." }
ASSERT
  ("no_zero_total_no_purchases",
    `
  SELECT
    COUNT(*)
  FROM
    agg
  WHERE
    total_no_purchases = 0 `) { description: "Ensure 'total_no_purchases' is not zero. A value of zero would lead to division by zero in the calculation of 'avg_purchased_items'." }
  --Final select
SELECT
  month,
  traffic_source_medium,
  purchased_value_in_usd,
  total_purchased_items,
  ROUND(total_purchased_items / total_no_purchases, 2) AS avg_purchased_items
FROM
  agg
